outpath='/nfs/dust/cms/user/swieland/trees1124/' # path of output of analyzer
scriptpath='scriptsNov24' # folder containing shell scripts that will have to be run on cluster
samplelist='SampleListNov21.csv' # samples list
dataset_column='boosted_dataset' # run on the column with dataset or boosted_dataset?
cmsswcfgpath='/nfs/dust/cms/user/swieland/CMSSW_8_0_12/src/BoostedTTH/BoostedAnalyzer/test/boostedAnalysis_boostedjets_cfg.py'
cmsswpath='/nfs/dust/cms/user/swieland/CMSSW_8_0_12/'
dbs="prod/phys03" # dbs instance: boosted miniaod is in prod/phys03, standard miniaod in prod/global
min_events_per_job=50000 # min number of events per job
systematics=False # create extra trees with JES/JER systematics?
isBoostedMiniAOD=True # do the inputs contain fat jets?
analysisType='SL' # this is usually SL
