outpath='/nfs/dust/cms/user/hmildner/trees1124/' # path of output of analyzer
scriptpath='scriptsFeb17' # folder containing shell scripts that will have to be run on cluster
samplelist='SampleListSummer16_short.csv' # samples list
dataset_column='skimmed_dataset' # run on the column with dataset or boosted_dataset?
cmsswcfgpath='/afs/desy.de/user/h/hmildner/CMSSW_8_0_25/src/BoostedTTH/BoostedAnalyzer/test/boostedAnalysis_cfg.py'
cmsswpath='/afs/desy.de/user/h/hmildner/CMSSW_8_0_25/'
dbs="prod/phys03" # dbs instance: boosted miniaod is in prod/phys03, standard miniaod in prod/global
min_events_per_job=50000 # min number of events per job 
systematics=False # create extra trees with JES/JER systematics?
isBoostedMiniAOD=False # do the inputs contain fat jets?
analysisType='SL' # this is usually SL
