outpath='/nfs/dust/cms/user/epfeffer/ntupling/ttbar_and_ttbb' # path of output of analyzer
scriptpath='ttbar_and_ttbb' # folder containing shell scripts that will have to be run on cluster
samplelist='ttH_legacy_samples_2018.csv' # samples list
dataset_column='dataset' # run on the column with dataset or boosted_dataset?
cmsswcfgpath='/nfs/dust/cms/user/epfeffer/BoostedTTH/CMSSW_10_2_18/src/BoostedTTH/BoostedAnalyzer/test/cfg_ttbb_analysis.py'
cmsswpath='/nfs/dust/cms/user/epfeffer/BoostedTTH/CMSSW_10_2_18'
dbs="prod/global" # dbs instance: boosted miniaod is in prod/phys03, standard miniaod in prod/global
min_events_per_job=100000 # min number of events per job 
isBoostedMiniAOD=False # do the inputs contain fat jets?
systematicVariations='noSysts.txt'
nSystematicVariationsPerJob=4
ProduceMemNtuples=False
